### PR TITLE
Support binary payload

### PR DESCRIPTION
**Pull request by yunxianggu99**
Support binary payload

### CODE REVIEW

**Comment by yunxianggu99** [comment]
Followed the `binaryEncode` method in JS serializer. But the first byte is zero according to that logic? Am I missing something here?

```
let offset = 0
view.setUint8(offset++, this.KINDS.push) // kind
```
where `this.KINDS.push === 0`

**Comment by sherbondy** [comment]
> Followed the `binaryEncode` method in JS serializer. But the first byte is zero according to that logic? Am I missing something here?
> 
> ```
> let offset = 0
> view.setUint8(offset++, this.KINDS.push) // kind
> ```
> 
> where `this.KINDS.push === 0`

Sorry, what’s the problem with the first byte being 0? Don’t have any context?

**Comment by yunxianggu99** [comment]
Because the actual payload from web is not 0. Also backend throws `Jason.decodeError` if the first byte is 0

**Comment by sherbondy** [comment]
> Because the actual payload from js client is not 0. Also backend throws `Jason.decodeError` if the first byte is 0

Ok, then why not step through the JS implementation and see where the behavior is diverging?

**Comment by yunxianggu99** [comment]
Error log:

```
[error] GenServer #PID<0.1883.0> terminating
** (Jason.DecodeError) unexpected byte at position 0: 0x0
    (jason 1.4.0) lib/jason.ex:92: Jason.decode!/2
    (phoenix 1.7.3) lib/phoenix/socket/serializers/v1_json_serializer.ex:31: Phoenix.Socket.V1.JSONSerializer.decode!/2
    (phoenix 1.7.3) lib/phoenix/socket.ex:503: Phoenix.Socket.__in__/2
    (websock_adapter 0.5.1) lib/websock_adapter/cowboy_adapter.ex:24: WebSockAdapter.CowboyAdapter.websocket_handle/2
    (cowboy 2.10.0) /Users/yunxiang/betafi/deps/cowboy/src/cowboy_websocket.erl:528: :cowboy_websocket.handler_call/6
    (cowboy 2.10.0) /Users/yunxiang/betafi/deps/cowboy/src/cowboy_http.erl:257: :cowboy_http.loop/1
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.2135813886.319291397.132683>, :process, #PID<0.1869.0>, {%Jason.DecodeError{position: 0, token: nil, data: <<0, 2, 2, 23, 18, 49, 48, 49, 51, 112, 97, 114, 116, 105, 99, 105, 112, 97, 110, 116, 58, 54, 50, 49, 58, 115, 95, 57, 100, 120, 119, 57, 112, 117, 98, 108, 105, 115, 104, 95, 97, ...>>}, [{Jason, :decode!, 2, [file: 'lib/jason.ex', line: 92, error_info: %{module: Exception}]}, {Phoenix.Socket.V1.JSONSerializer, :decode!, 2, [file: 'lib/phoenix/socket/serializers/v1_json_serializer.ex', line: 31]}, {Phoenix.Socket, :__in__, 2, [file: 'lib/phoenix/socket.ex', line: 503]}, {WebSockAdapter.CowboyAdapter, :websocket_handle, 2, [file: 'lib/websock_adapter/cowboy_adapter.ex', line: 24]}, {:cowboy_websocket, :handler_call, 6, [file: '/Users/yunxiang/betafi/deps/cowboy/src/cowboy_websocket.erl', line: 528]}, {:cowboy_http, :loop, 1, [file: '/Users/yunxiang/betafi/deps/cowboy/src/cowboy_http.erl', line: 257]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
```

**Comment by sherbondy** [comment]
> Phoenix.Socket.V1.JSONSerializer.decode!

Awesome, so clearly something wrong with the incoming message, as you should be hitting the `decode_binary` path if you're encoding as binary.

So there's something wrong with the encoding.
You can actually step through the implementation and see why your current incoming socket payload request is triggering the `text` branch when it should be hitting the `binary` branch here:

https://github.com/phoenixframework/phoenix/blob/893d0f9e37081a2bd3ba76a038610a86a8714a09/lib/phoenix/socket/serializers/v2_json_serializer.ex#L105-L110

yea?

`ops[:opcode]` is getting set to `:text` for your payload when it should be `:binary`.

Callsite for this is here:
https://github.com/phoenixframework/phoenix/blob/9dd4689443bd94539ca6c6cc430afeb5fe3f85dc/lib/phoenix/socket.ex#L502-L505

this is the raw underlying fn for `handle_in`

**Comment by yunxianggu99** [comment]
Simplified code a bit while still hitting the same decode error: seems what gets passed is number 0 while decoder expects '0' (i.e. 48)? Although following [this](https://github.com/phoenixframework/phoenix/blob/673f739b91edd5525401e162aa40343aef61a2e3/assets/js/phoenix/serializer.js#L31) step by step
- we have four metadata, namely: `joinRef`, `ref`, `topic`, `event` (all `string` type)
- so building an `UInt8` array with the length of the four metadata, and each character of the four metadata
- convert the `[UInt8]` to `Data` type, which is the Swift equivalent of JS `ArrayBuffer`
- then concatenate with the raw payload, which is also of `Data` type (in swift, can do `let concatData = data1 + data2`)
Not sure at which step is wrong

**Pull request closed without merging**
